<div id="launcher"> 
    <div id="staff_image" class="launchButton">
        <a href="<?php echo $this->baseUrl() . '/admin/staff/add'; ?>">Staff Add</a>
    </div>
    <div id="candidate_image" class="launchButton">
        <a href="<?php echo $this->baseUrl() . '/admin/candidate/add'; ?>">Candidate Add</a>
    </div>
    <div id="agent_image" class="launchButton">
        <a href="<?php echo $this->baseUrl() . '/admin/agent/add'; ?>">Agent Add</a>
    </div>
    <div id="stamping_image" class="launchButton">
        <a href="<?php echo $this->baseUrl() . '/admin/stamping/add'; ?>">Stamping Add</a>
    </div>
    <div id="medical_image" class="launchButton">
        <a href="<?php echo $this->baseUrl() . '/admin/medical/add'; ?>">Medical Add </a>
    </div>
    <div id="company_image" class="launchButton">
        <a href="<?php echo $this->baseUrl() . '/admin/company/add'; ?>">Company Add</a>
    </div>
    <div id="category_image" class="launchButton">
        <a href="<?php echo $this->baseUrl() . '/admin/category/add'; ?>">Category Add</a>
    </div>
</div>