<div class="texture">
    <section class="intro">
        <div class="line-left"></div>
        <div class="line-right"></div>
        <h1>
            <div class="small"> What is Destiny? </div>
            <p class="define">The Destiny is here to help you get from where you are to where you want to be. It’s packed with tips, tools, resources and the practical stuff you need to know about starting a career, making the most of your salary and getting yourself set up on your journey to success.</p>
        </h1>
    </section>
</div>