<?php echo $this->hello; ?>
<div class="span12 hero-unit">
    <div class="top-hero-unit">
        <div class="span7 hero-unit">
            <div class="slider-wrapper theme-default">
                <div id="slider" class="nivoSlider">
                    <img src="<?php echo $this->baseUrl() . '/destiny/front/front/front1.jpg'; ?>" data-thumb="<?php echo $this->baseUrl() . '/destiny/front/gallery/paru.jpg'; ?>" alt="" title="We provide you best service in the industry." />
                    <img src="<?php echo $this->baseUrl() . '/destiny/front/front/front2.jpg'; ?>" data-thumb="<?php echo $this->baseUrl() . '/destiny/front/gallery/pooja.jpg'; ?>" alt="" title="Destiny is perfect platform to choose your destination." />
                    <img src="<?php echo $this->baseUrl() . '/destiny/front/front/front3.jpg'; ?>" data-thumb="<?php echo $this->baseUrl() . '/destiny/front/gallery/suman.jpg'; ?>" alt="" title="We fit right people in right job." data-transition="slideInLeft" />
                    <img src="<?php echo $this->baseUrl() . '/destiny/front/front/front4.jpg'; ?>" data-thumb="<?php echo $this->baseUrl() . '/destiny/front/gallery/prakash.jpg'; ?>" alt="" title="We fit right people in right job." />
                    <img src="<?php echo $this->baseUrl() . '/destiny/front/front/front5.jpg'; ?>" data-thumb="<?php echo $this->baseUrl() . '/destiny/front/gallery/shyam.jpg'; ?>" alt=""  title="We fit right people in right job." />
                    <img src="<?php echo $this->baseUrl() . '/destiny/front/front/front6.jpg'; ?>" data-thumb="<?php echo $this->baseUrl() . '/destiny/front/gallery/team.jpg'; ?>" alt="" data-transition="slideInRight" title="We fit right people in right job." />
                    <img src="<?php echo $this->baseUrl() . '/destiny/front/front/front7.jpg'; ?>" data-thumb="<?php echo $this->baseUrl() . '/destiny/front/gallery/team.jpg'; ?>" alt="" data-transition="slideInRight" title="We fit right people in right job." />
                </div>
            </div>
        </div>
    </div>
    <div class="span2 hero-unit">
        <p class="f-two">Join Us!!</p>
        <p class="f-two">We guide in your every step to search</p><p>the best jobs that suits with your qualification, experience & knowledge. </p>
    </div>
</div><!--            span11 hero-unit div ends-->
<div class="clear"></div>
<div class="link-four">
    <div class="row-fluid span12">
        <div class="span3 hero-unit">
            <a href="<?php echo $this->baseUrl() . '/index/form'; ?>"><img src="<?php echo $this->baseUrl() . '/destiny/front/images/img/application.jpg'; ?>" alt="" /> <strong>Make An Application</strong></a>
        </div>
        <div class="span3 hero-unit">
            <a href="<?php echo $this->baseUrl() . '/downloads/dps.pdf'; ?>"><img src="<?php echo $this->baseUrl() . '/destiny/front/images/img/prospectus.jpg'; ?>" alt="" /> <strong>Order A Prospectus</strong></a>
        </div>
        <div class="span3 hero-unit">
            <a href="#"><img src="<?php echo $this->baseUrl() . '/destiny/front/images/img/fees.jpg'; ?>" alt="" /> <strong>Fees &amp; Funding</strong></a>
        </div>
        <div class="span3 hero-unit">
            <a href="#"><img src="<?php echo $this->baseUrl() . '/destiny/front/images/img/newdemand.jpg'; ?>" alt="" /> <strong>View New Demand</strong></a>
        </div>
    </div>
</div>



<script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
</script>