<div class="span11 hero-unit">
    <div class="span6 hero-unit">
        <div class="slider-wrapper theme-default">
            <div id="slider" class="nivoSlider">
                <img src="<?php echo $this->baseUrl() . '/destiny/front/gallery/paru.jpg'; ?>" data-thumb="<?php echo $this->baseUrl() . '/destiny/front/gallery/paru.jpg'; ?>" alt="" title="We provide you best service in the industry." />
                <img src="<?php echo $this->baseUrl() . '/destiny/front/gallery/pooja.jpg'; ?>" data-thumb="<?php echo $this->baseUrl() . '/destiny/front/gallery/pooja.jpg'; ?>" alt="" title="Destiny is perfect platform to choose your destination." />
                <img src="<?php echo $this->baseUrl() . '/destiny/front/gallery/suman.jpg'; ?>" data-thumb="<?php echo $this->baseUrl() . '/destiny/front/gallery/suman.jpg'; ?>" alt="" title="We fit right people in right job." data-transition="slideInLeft" />
                <img src="<?php echo $this->baseUrl() . '/destiny/front/gallery/prakash.jpg'; ?>" data-thumb="<?php echo $this->baseUrl() . '/destiny/front/gallery/prakash.jpg'; ?>" alt="" title="We fit right people in right job." />
                <img src="<?php echo $this->baseUrl() . '/destiny/front/gallery/shyam.jpg'; ?>" data-thumb="<?php echo $this->baseUrl() . '/destiny/front/gallery/shyam.jpg'; ?>" alt=""  title="We fit right people in right job." />
                <img src="<?php echo $this->baseUrl() . '/destiny/front/gallery/team.jpg'; ?>" data-thumb="<?php echo $this->baseUrl() . '/destiny/front/gallery/team.jpg'; ?>" alt="" data-transition="slideInRight" title="We fit right people in right job." />
            </div>
        </div>
    </div>
    <div class="span2 hero-unit">
        <p>Join Us!!</p>
        <p>We guide in your every step to search the best jobs that suits with your qualification, experience & knowledge. </p>
    </div>
</div><!--            span11 hero-unit div ends-->

<div class="span11 hero-unit">

    <p><h3>Services<h3></p>
            <div class="left-para">
                <p><h5>Executive Search & Selection</h5></p>
                <p><h5>Search & Selection of Manpower for the sponsor</h5></p>
                <p><h5>Immigration Services</h5></p>
                <p><h5>Obtain visa for worker visa</h5></p>
                <p><h5>  Expatriate/Foreign Worker & Department Employment Passes</h5></p>
                <p><h5>Permission obtain from Labour Ministry</h5></p>
                <p><h5>  Employment support</h5></p>
                <p><h5>Employment law & regulations</h5></p>
                <p><h5>Manpower recruitment plan</h5></p>
                <p><h5> Employers Policy, Guidelines & Handbooks</h5></p>
                <p><h5>Manpower supply</h5></p>
                <p><h5>Recruitment & Supply of skilled/Manual labour</h5></p>
            </div>
            </div><!--span11 hero-unit div ends-->


            <script type="text/javascript">
                $(window).load(function() {
                    $('#slider').nivoSlider();
                });
            </script>