<p>Is this Candidate has taken the Orientation Class?</p>
<form action="<?php echo $this->baseUrl() . '/admin/stamping/orientation-test/id/' . $this->id; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->message['id']; ?>" />
        <input type="submit" name="orientation" value="Yes" />
        <input type="submit" name="orientation" value="No" />
    </div>
</form>

